title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156/proj-scaffold
owner: ucsb-cs156
repo_name: proj-scaffold
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-Claude-issue69","number":79,"title":"Replace SyncPlRepoJob with course-scoped SyncCourseWithPlRepoJob","url":"https://github.com/ucsb-cs156/proj-scaffold/pull/79"},{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/implement-editing-of-concepts","number":78,"title":"Implement editing and deletion of Concepts and Subconcepts","url":"https://github.com/ucsb-cs156/proj-scaffold/pull/78"}]
