
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-scaffold
owner: ucsb-cs156
repo_name: proj-scaffold
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-fix-scrolling-css","number":22,"title":"pc - fix #19: scroll lock only on Scaffold Canvas pages; consolidate custom CSS","url":"https://github.com/ucsb-cs156/proj-scaffold/pull/22"},{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/debug-mode-for-admin-instructors","number":21,"title":"[WIP] Add debug mode toggle for Admin and Instructors","url":"https://github.com/ucsb-cs156/proj-scaffold/pull/21"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-add-backend-CRUD-Concept","number":18,"title":"Pc add backend crud concept","url":"https://github.com/ucsb-cs156/proj-scaffold/pull/18"}]
